INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computer',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car&Audio',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kids Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women Wear',NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men Wear',NOW());